backend/.dockerignore, backend/Dockerfile, backend/app.py, docker-compose.yml, frontend/.dockerignore, frontend/Dockerfile, frontend/vite.config.js
Added dockerfile & Docker Compose 
- [ ☑️] I am an Open Source contributor
- [ ☑️] I have performed a self-review of my code
- [ ☑️] My code follows the style guidelines of this project
- [ ☑️] I have commented on my code, particularly in hard-to-understand areas
=> Added dockerfile & docker-compose

README.md
Closes #
Added docker-compose.yml about Docker setup and utilisation 
Added environment variable in docker-compse.yml
=> Update README.md about Docker setup and utilisation 

frontend/src/styles/pages/_landingpage.scss
Closes #30
Fixed a styling issue on the landing page. The styling of the .faq-div was changed to ensure that image section remains stable and unaffected due to the expansion of the accordians in the adjacent section of "Any Queries?"
=> Fix Landing page styling

frontend/src/components/form/Accountform.jsx
=> new-phone-validation 

README.md, backend/.env.example, frontend/.env.example
Added `.env.example` files which were deleted in recent merged PR #56
=> Add env example and Updated env setup guidelines

frontend/src/data/footerData.jsx
Add Github link with icon in Footer #22
Made changes to the ../frontend/src/data/footerData.jsx
=> Added GitHub link to the footer 

frontend/src/components/common/Footer.jsx
Closes #66 
Refactored the footer list items to ensure proper alignment across all screen sizes. Updated the layout and styling to enhance consistency and readability.
=> Refactor footer list items to align properly

.github/EnvVarSetUpGuideline.md, README.md
Fixes issue #45 
Closes #45 
What the PR adds: A new guideline file for .env variable setup.
What the PR modifies: Adds a link in README.md.
Emphasize that no other changes are made.
- [+] Documentation (non-breaking change which updates or adds documentation)
- [+] I am an Open Source contributor
- [+] I have performed a self-review of my code
- [+] My code follows the style guidelines of this project
- [+] I have commented on my code, particularly in hard-to-understand areas
Can you please review this @PratikMane0112
=> docs : Add environment variables setup guidelines and link to README

frontend/package-lock.json, frontend/src/data/footerData.jsx, frontend/src/pages/AboutUs.jsx, frontend/src/routes/RouterRoutes.jsx, frontend/src/styles/pages/AboutUs.scss
Added AboutUs.jsx,AboutUs.scss,Modified footerData.jsx and RouterRoutes.jsx
https://github.com/user-attachments/assets/b82cacc3-e6d1-44b2-846b-2352b00302ed
=> Added AboutUs.jsx,AboutUs.scss,Modified footerData.jsx and RouterRoutes.jsx

frontend/src/pages/LandingPage.jsx
Closes #38  
I have update the branch to avoid unnecessary changes
- [✅ ] Style (non-breaking change which improves website style or formatting)
- [✅ ] I am an Open Source contributor
- [ ✅] I have performed a self-review of my code
- [ ✅] My code follows the style guidelines of this project
- [✅ ] I have commented on my code, particularly in hard-to-understand areas
=> corrected_landingPage_issue

backend/.gitignore, backend/app.py, frontend/package-lock.json
Closes #
- Add a link to forgot password page
- send an post request to forgot email endpoint
- it will send an email with access token and add a expiration token to db
-  then when the user clicks on the link it sends a POST request to reset-password where the user updates his new password
=> Added forgot password

frontend/src/components/diseasePrediction/Home.jsx
Closes #64 
- Have not deleted `_diseaseprediction.scss` since other components rely on it
https://github.com/user-attachments/assets/94adf59d-a4cb-4ef6-a80c-7b201bd02675
=> Converted styling of Home.jsx in disease prdiction

frontend/package-lock.json, frontend/package.json, frontend/src/components/medicines/ProductCard.jsx, frontend/src/pages/Feedback.jsx, frontend/tailwind.config.js
Closes #64 
- Installed `tailwind-scrollbar` utility and imported it in `tailwind.config.js`
https://github.com/user-attachments/assets/f496580c-689b-4ea2-8b25-4a0ac8b5aba0
=> Feature/convert styling of product card.jsx

frontend/src/components/medicines/FilterBar.jsx
Closes #64 
- Enhanced visibility of `Filterbar.jsx` for different-screens.
Befor:
https://github.com/user-attachments/assets/478e168e-7fed-4e95-896e-bf0863f96571
After changes:
https://github.com/user-attachments/assets/5efefbe8-8ae5-40e5-ad77-95691b733caa
=> Feature/enhanced styling of filter bar.jsx

frontend/src/components/medicines/FilterBar.jsx, frontend/src/pages/ErrorPage.jsx, frontend/src/styles/style.scss
Closes #64 
-  Removed import of errorpage.scss
Uploading Recording 2025-01-13 113641.mp4…
=> Feature/convert styling of error page.jsx

frontend/src/components/medicines/FilterBar.jsx, frontend/src/components/medicines/ProductCard.jsx, frontend/src/components/medicines/TopProducts.jsx, frontend/src/pages/ErrorPage.jsx, frontend/src/styles/style.scss
Closes #64 
https://github.com/user-attachments/assets/4dbf135e-461c-43db-a6a3-a359e1d2204b
=> Feature/convert styling of TopPoducts.jsx

frontend/src/components/medicines/FeaturedProducts.jsx, frontend/src/components/medicines/FilterBar.jsx, frontend/src/components/medicines/ProductCard.jsx, frontend/src/components/medicines/TopProducts.jsx, frontend/src/pages/ErrorPage.jsx, frontend/src/styles/style.scss
Closes #64 
https://github.com/user-attachments/assets/7107ea0c-4092-4398-8931-249493dc2d46
=> Feature/convert styling of fetured products.jsx

frontend/src/components/medicines/FilterBar.jsx, frontend/src/components/medicines/FilterBarOptions.jsx, frontend/src/components/medicines/ProductCard.jsx, frontend/src/components/medicines/TopProducts.jsx, frontend/src/contexts/filters/filterContext.jsx, frontend/src/pages/AllMedicines.jsx
Closes #64 
1. **Converted Styling of FilterBar:** Improved and streamlined styling for better maintainability.
Befor:
https://github.com/user-attachments/assets/478e168e-7fed-4e95-896e-bf0863f96571
After changes:
https://github.com/user-attachments/assets/2ad1f90b-f035-4639-bfca-c39632c0512f
=> Converted styling of FilterBar and made it responsive

backend/app.py
Added a Backend route to save user feedBack based on Feature Request #137
=> Add route for FeedBack

frontend/src/components/common/SearchBar.jsx, frontend/src/hooks/useActive.js, frontend/src/pages/MedicineDetails.jsx
Closes #64 
1. Converted Styling of `MedicineDetails.jsx` page
2. Updated useActive.js hook
3. `_medicineDetails.scss` is yet to be deleted to convert other component
useActive.js
Referense to how useActive.js hook has been used for other contributors
https://github.com/user-attachments/assets/c29565ff-9947-40d1-b954-30a8d3074392
=> Converted styling of MedicineDetails.jsx

frontend/src/pages/Failed.jsx
Closes #64 
1. Converted Styling of `Failed.jsx` component
https://github.com/user-attachments/assets/0b5e34d1-c9f3-4da4-8d7f-6435f433f4d2
=> Converted styling of Failed.jsx

frontend/src/pages/DisPred.jsx, frontend/src/styles/pages/_dispred.scss, frontend/src/styles/style.scss
Closes #64 
1. Converted Styling of `DisPred.jsx` component
3. deleted `_DisPred.scss` and its import
https://github.com/user-attachments/assets/7f39d6f0-2f41-407c-a372-54f4ff63cf97
=> Converted styling of DisPred.jsx

frontend/src/components/diseasePrediction/Home.jsx, frontend/src/pages/DiseasePrediction.jsx
Closes #64 
1. Converted Styling of `DiseasePrediction.jsx` page
4. `_DiseasePrediction.scss` is yet to be deleted to convert other components
https://github.com/user-attachments/assets/df4e3edd-fa19-477a-ab04-9ddbed48c290
=> Converted styling of DiseasePrediction.jsx

frontend/src/pages/Cart.jsx, frontend/src/pages/MyWallet.jsx, frontend/src/pages/RecentTransactions.jsx
Closes #64 
1. Converted Styling of `RecentTransactions.jsx` component
https://github.com/user-attachments/assets/5293bb43-99b0-4161-abcd-9302ae9592a8
=> Converted styling of RecentTransactions.jsx

frontend/src/pages/Doctors.jsx
This PR fixes a part of Issue #64. Reference #175 and #181 
Migrated all of the scss code of doctors page to tailwind classes as per requirements. 
https://github.com/user-attachments/assets/250aeae0-969f-4363-9a28-46153a1e97fe
=> feat: fixed doctor page ui

frontend/src/pages/Home.jsx
This PR fixes a part of Issue #64 . Refer #174 
Migrated all of the scss code of home page to tailwind classes as per requirements.
=> feat: fixed home page ui

frontend/src/components/form/Accountform.jsx, frontend/src/styles/base/_form.scss, frontend/src/styles/style.scss
Replaced code inside Accoundform.jsx to be styled by older scss file
=> Replaced code inside Accoundform.jsx to be styled by older scss file

frontend/src/components/common/ChatBot.jsx, frontend/src/pages/Doctors.jsx
This PR fixes the modal and div close issue occurred by non implementation of useOutsideClose() Hook in doctor.jsx and chatbot.jsx
Fixes #184  and Closes it
Added proper hook and ref control to both the pages and managed the useOustideClose Hook in both the pages
https://github.com/user-attachments/assets/92be669c-63c5-4b8c-ac01-b4686da35db1
https://github.com/user-attachments/assets/2e484f84-50b5-4671-9275-13572b9eac71
=> fix: useOutsideClose hook not working in doctor and chatbot pages

.github/EnvVarSetUpGuideline.md, backend/.env.example
Related to #194 
**Updated EnvVarSetUpGuideline.md and backend/.env.example for new Twilio .env variables**
1. EnvVarSetUpGuideline.md
https://github.com/user-attachments/assets/f8ed1d69-3b4e-4fe1-a0aa-4dc5cd050a1f
2. backend/.env.example
=> Updated EnvVarSetUpGuideline.md and backend/.env.example

backend/app.py, frontend/src/components/resetPassword/ResetPassword.jsx, frontend/src/routes/RouterRoutes.jsx
Closes #110 
This PR adds forgot password to the frontend and modifies backend to work specifically with the frontend endpoints.
https://github.com/user-attachments/assets/91b1a101-ed65-4e67-9de0-8d53e2f9b14f
=> feat: added forgot password backend and frontend

frontend/src/pages/Feedback.jsx
Fixes a Part of Issue #137 
This PR fixes adds backend integration to feedback page and necessary logics
https://github.com/user-attachments/assets/2aff05bf-999f-4fae-80ac-d88c40c94726
=> feat: added backend integration and improved ui

frontend/src/pages/Doctors.jsx
Closes _none_
To ensure that appointment scheduling works correctly, the following changes were made:  
1. **Fixed Incorrect Route:**  
- `handleScheduleClick` was calling a non-configured route `/scheduale_meeting`.  
- Updated it to `/set_appointment` to match the correct endpoint.  
2. **Ensured Proper Appointment Reflection:**  
- Previously, appointments were being confirmed but not properly reflected for both doctors and patients.  
- Based on the project’s previous logic, I resolved this issue—appointments are now correctly confirmed and displayed in upcoming appointments.  
- In the **second attached video**, I compared the current and old styling.  
- Debugging this issue took considerable time to test the full appointment flow.  
- There are noticeable styling changes, …
=> Fixed issue of meeting not getting scheduled

frontend/src/pages/Doctors.jsx
Closes #204 
This PR includes several improvements and fixes:
1. **Updated Styling:**
- Improved overall styling for a more polished and consistent look across the app.
- Enhanced responsiveness for better user experience across different screen sizes.
2. **Fixed DataGrid Element:**
- Corrected issues related to the `DataGrid` element, ensuring proper alignment, data rendering, and interaction functionality.
3. **Fixed Availability Logic for Dates:**
- The previous code was not updating unavailable dates based on the current date. Now, the availability of time slots is checked and updated daily, reflecting the correct status of each time slot for the current day.
- Time slots that are selected once now remain unavailable only for the current day, preventing them from being marked …
=> Feature/update styling and functionality of Doctors.jsx

frontend/package.json
Build error
Added
```json
"lucide-react": "^0.474.0",
```
=> Added lucide-react in package.json

frontend/src/App.jsx, frontend/src/components/common/Cursortrail.jsx
Closes #200 
I added a cursor trail to the site, its just design the website a little bit 
Added a cursor trail component 
https://github.com/user-attachments/assets/11469342-f522-4503-87d2-dfddcbcfb981
=> added cursor trail

frontend/package-lock.json, frontend/src/components/common/ChatBot.jsx
Closes #166
1. Fixed incorrect responses by adding a system prompt at the start of the conversation.
2. Ensured the chatbot follows its role as a medical assistant and provides relevant and context-aware responses.
3. Improved response handling to prevent out-of-context replies.
=> Fixed the response of TelMedBot

backend/app.py, frontend/.gitignore, frontend/src/components/common/Header.jsx, frontend/src/components/form/Accountform.jsx, frontend/src/index.css
Closes #154 
1. **Firebase Configuration**:
- Loaded necessary Firebase credentials from `telmedsphere-firebase-adminsdk.json` (file is ignored by `.gitignore`).
2. **Google Sign-in Integration**:
- Updated both `login` and `register` functions to support Google-based authentication through Firebase.
- During Google login or registration, the required fields are populated automatically, avoiding logical errors due to missing values.
3. **Default Field Handling**:
- Ensured that default values are assigned to missing fields for both patients and doctors during registration if Google Sign-in is used. This guarantees consistency across user data.
4. **Firebase Credentials Security**:
- Updated `.gitignore` to ensure the Firebase service account file `telmedsphere-firebase-adminsdk.json` is …
=> Integrate Google Sign-in for User Registration and Login, with Default Values Handling and Firebase Configuration

README.md
Closes #235 
This pull request includes updates to the `README.md` file to add a section about the project's license. The most important changes are:
Documentation updates:
* Added a link to the license section in the table of contents. (`README.md` [README.mdR38](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R38))
* Added a new section detailing the project's license, including a link to the Apache License 2.0 and the full license text.
=> added license section

backend/app.py, backend/templates/email.html, backend/utils/imageUploader.py
Closes #242 
- Added Cloudinary integration for managing image and file uploads, improving file handling and storage.
- Created a `utils` folder inside the backend and added an `imageUploader.py` file.
- Created the `upload_file` function in `imageUploader.py` and imported it in `app.py`.
- Modified the `mail_file` function in `app.py` to:
- Upload the receipt to Cloudinary.
- Retrieve its public URL (secure URL) for sending over WhatsApp.
- Added TelMedSphere's logo to the email template for branding purposes.
- Reformatted the email content to make it more empathetic towards the patient, improving the tone and user experience.
https://github.com/user-attachments/assets/6a5463e4-1099-4f2a-a3e8-a6eecccbc349
=> Integrated Cloudinary for File Uploads, Updated Email Template, and Sent Receipt Link in WhatsApp

frontend/src/pages/MeetPage.jsx
Closes #245 
- Adjusted the **Meet screen size** to ensure proper visibility on all screen sizes.  
- Ensured **each button and input** has the appropriate **background color, text, and box-shadow** for better UI consistency.  
- Improved UI for **multiple prescription items** to enhance readability and user experience.  
- Mapped old styling classes and continuously checked previous styles by **importing old `MeetPage.jsx` and its style dependencies** for reference while making changes.  
https://github.com/user-attachments/assets/efb6802f-3d8a-456d-9ae2-a360814c0c1b
https://github.com/user-attachments/assets/36755029-955e-4aa8-92bf-310e753af632
=> Updated styling of MeetPage.jsx

frontend/package-lock.json, frontend/src/components/form/Accountform.jsx, frontend/src/pages/ContactUs.jsx
**# Fixes Issue #231🛠️**
**# Description👨‍💻**
I have improved the **Contact Page** by adding interactive **hover effects** to enhance user experience and make the UI more engaging.  
🔹 **Input Fields:**  
- Now, when users hover over the **name, email,  and message fields**, the border color changes to a sleek **blue highlight** , improving visibility and accessibility.  
- A subtle **box shadow effect** is added to give a modern touch.  
- Smooth **transition effects** ensure a seamless interaction when focusing or hovering over fields.  
🔹 **Textarea (Message Box):**  
- The message input area now includes a **hover glow effect** and **resizable feature**  for better usability.  
🔹 **Submit Button:**  
- A new **hover animation**  gives the button a floating effect.  
- The background …
=> 🚀 Enhanced Contact Page with Hover Effects 📝 

frontend/src/components/numberedCard/AnimatedCounter.jsx, frontend/src/pages/LandingPage.jsx
Closes #258  
Currently, the website lacks a **social proof section** that highlights the number of satisfied customers and their ratings. Adding this feature will help build **trust and credibility** among potential users, increasing conversions and engagement.  
✅ **Added a "DetailsBar" section** to showcase key statistics.  
✅ **Smooth animations using Framer Motion** for an interactive experience.  
✅ **Responsive layout** for mobile, tablet, and desktop.  
✅ **Optimized text sizes** for readability and UI consistency.  
✅ **Implemented a modern design** with Tailwind CSS.  
✔ **100,000+ Satisfied Patients** – Highlights the number of users who have successfully used the platform.  
✔ **4.8★ Average Rating** – Displays aggregated ratings from patients.  
✔ **1,000+ Certified Doctors** …
=> numbered card added (Closes #258)

backend/app.py
Closes #252 
This PR enhances user profile management by allowing users to upload a profile picture. The uploaded image is stored in **Cloudinary**, and the **image URL is saved in the database**. When users update their profile, the profile picture URL is retrieved and sent to the frontend. If no profile picture is uploaded, a **default profile picture** is assigned.  
Additionally, this PR **converts the request format from JSON to `multipart/form-data`**, ensuring smooth handling of file uploads alongside other user details.  
- **Converted request format from JSON to `multipart/form-data`** to support file uploads.  
- If a profile picture is uploaded, it is **stored in Cloudinary**, and the **URL is saved in the DB**.  
- The profile picture URL is sent in the response for the …
=> Add Profile Picture Upload Functionality Using Cloudinary (Backend)

backend/app.py, frontend/src/components/common/Header.jsx, frontend/src/components/common/Profile.jsx, frontend/src/components/form/Accountform.jsx, frontend/src/contexts/common/commonReducer.js
Closes #266
- The `doctorId` field was not being stored or handled anywhere in the frontend or backend.  
- Now, `doctorId` is correctly assigned for **all authentication types** (email/password and Google login).  
- Ensured proper storage and retrieval of `doctorId` for doctors.  
- Updated backend logic to handle `doctorId` correctly when registering/logging in users.  
---
- **Added a loading spinner** that is visible until the profile picture is fully loaded, improving UI responsiveness.  
- **Centralized profile picture storage logic in `commonReducer`** instead of handling it separately in multiple components.  
- **Ensured profile pictures persist correctly across sessions** without flickering or requiring manual reloads.  
---
- Implemented **automatic page reload** after …
=> Doctor ID Handling, Profile Picture Management, Auto Page Reload & More  

backend/app.py, frontend/src/pages/Home.jsx
Closes #265 
- Previously, the rating logic **registered a lower value than intended**, leading to inaccurate reviews.  
- This issue is now resolved, ensuring that **the correct rating value is stored and displayed** consistently.  
**Before:**  
- No clear indication of availability updates, making the process unclear for doctors.  
- Clicking "Available" multiple times unnecessarily triggered state updates, leading to inefficiencies.  
**Now:**  
- A **proper progress animation** has been added when a doctor changes availability.  
- A **smooth transition from 0% to 100% progress** visually indicates the status update.  
- The **button is disabled once the doctor sets availability** to prevent redundant API calls.  
- The UI and state management are now more **efficient and …
=> Fixed Rating Bug & Enhanced Doctor Availability Indication

backend/app.py, frontend/src/components/landingPage/TestimonialCarousel.jsx
Closes #278 
- Updated `/feedback` **POST** route to store additional patient details:  
- **Username** (fetched from `patients` collection)  
- **Profile picture** (fetched from `patients` collection)  
- Ensured feedback objects now contain:  
```python
feedback_entry = {
"doctor_email": doctor_email,
"patient_email": patient_email,
"rating": rating,
"feedback_message": feedback_message,
"username": patient.get("username", ""),
"profile_picture": patient.get("profile_picture", ""),
}
- Minor improvements and fixes in feedback-related routes.
- Correctly fetches feedbacks from the backend, ensuring all fields are displayed.
- Displays profile pictures, usernames, feedback messages, and ratings properly.
https://github.com/user-attachments/assets/eb8b7ed7-8921-4a65-8211-16c3e00af0d7
=> Improve Feedback Handling & Infinite Testimonial Carousel

backend/app.py, frontend/src/components/landingPage/TestimonialCarousel.jsx, frontend/src/pages/Feedback.jsx
Closes #292
This PR enhances the feedback submission and display logic based on user preferences. Users can now choose whether their feedback is public or private. The UI has been updated to reflect these changes, ensuring a seamless experience.  
- Added a **checkbox** allowing users to opt-in/out of sharing their feedback publicly.  
- Ensured **profile pictures** are displayed correctly, whether from dynamic data or hardcoded sample data.  
- Updated the feedback **submission structure** to include:  
- `feedback_type`  
- `rating`  
- `comments`  
- `share_it_on_website`  
- `user_email`, `username`, `profile_picture`  
- `timestamp` (sent by frontend)  
- Modified **display logic**:  
- Feedback is shown **only if the user has approved it for public visibility**.  
- Testimonials are …
=> Enhance Frontend Logic for Feedback Submission and Public Visibility  

frontend/src/pages/LandingPage.jsx
Closes #255 
Complete the Landing page with required changes
UI Changes
=> Lottie Done

frontend/src/App.jsx, frontend/src/components/common/Header.jsx, frontend/src/contexts/DarkMode/DarkModeContext.jsx
Closes #288
**Changes Made:**
- Created `DarkModeContext.jsx` for toggling and storing dark mode preference in local storage.
- Wrapped `App.jsx` in `<DarkModeProvider>` to provide global dark mode context.
- Added a responsive UI toggle button for both small and large screen sizes.
- Enabled dark mode in Tailwind by configuring `tailwind.config.js`.
- **Main Highlight:** Implemented dark mode toggle without needing to import `DarkModeContext` in every component.
This PR ensures seamless dark mode integration across the project with minimal imports and efficient context usage.
https://github.com/user-attachments/assets/a438e9dc-8cf2-49de-b4e0-d6e286b3f9ac
=> Add Dark Mode Toggle with Global Context and Tailwind Support

frontend/src/pages/Checkout.jsx
This PR fixes #262 by integrating error handlers and enhancing ui. refer #275 and #276 
Closes #262 
The backend is correct only frontend changes were needed
=> fix: fixed checkout page error handling

frontend/src/components/common/Footer.jsx
#144 
Closes #144 
FOOTER ROUTE PROTECTION ADDED TO "buy-medicines" and generalised the footer protection to toggle form
=> feat: added protection to medicine route

backend/app.py, frontend/src/components/landingPage/TestimonialCarousel.jsx, frontend/src/pages/Doctors.jsx, frontend/src/pages/Home.jsx, frontend/src/pages/MeetPage.jsx, frontend/tailwind.config.js
Closes #301 
- New Route: Added a new route to add and fetch upcoming appointments for doctors.
-  Route Renaming: Renamed the route doctor_app to update_doctor_ratings for better clarity and updated its usage in the frontend accordingly.
-  Frontend Cleanup: Removed unnecessary logs from the frontend to improve performance and readability.
-  Email Field Consistency: Replaced email with demail/pemail wherever applicable to reduce confusion between doctor and patient email fields.
https://github.com/user-attachments/assets/97035f8a-424a-4cda-8d4b-acd6d1fb85e7
=> Added Upcoming Appointments Route, Renamed Doctor Ratings Route, Cleaned Logs, and Standardized Email Field

frontend/src/data/footerData.jsx
Added missing commas in footerData.jsx
=> Added missing commas in footerData.jsx

backend/app.py, frontend/src/data/footerData.jsx, frontend/src/pages/Doctors.jsx, frontend/src/pages/Home.jsx
Closes #296
This PR ensures that the **completed meet** is updated using a unified logic for both **scheduled** and **instant meets**.  
- Added a new **object** in `upcomingMeet` for both **doctor and patient** when an instant meet is created.  
- When a **patient gives feedback**, the **corresponding appointment** is **removed** from `upcomingMeet` for both users.  
- The **same appointment is added** to `completedMeet` with **all necessary fields**:  
- `demail`  
- `pemail`  
- `date`  
- `time`  
- `link`  
- `stars`  
- Renamed `doctor` collection access to `doctors` in `app.py` for consistency.  
This PR **only updates completedMeet when feedback is given from the frontend**.  
**Rendering of completed meets will be handled in a separate PR.** …
=> Implemented Logic to Update Completed Meet for Both Scheduled and Instant Meets

backend/app.py, frontend/src/pages/Home.jsx, frontend/src/pages/MeetPage.jsx
Closes #311
- Added a new API route to fetch completed meets for doctors and patients.
- Integrated it into the frontend with prescription access enabled.
- Handled cases where no history is found by adding a button to book an appointment.
https://github.com/user-attachments/assets/f45282be-c8be-4de9-8e44-a19305364465
=> Implemented new route to fetch completed meets

frontend/colors.js, frontend/src/components/common/Header.jsx
Closes #314 
Added Dark Theme for Header.jsx 
- Enhanced UI experience with dark mode support.
- Ensured seamless alignment with the project’s overall theme.
https://github.com/user-attachments/assets/fbcef82f-0a66-4aba-8d7e-a85899ffabed
https://github.com/user-attachments/assets/a902964d-d1d8-4aae-a841-4c0b9dff0fa1
=> Added Dark theme for Header.jsx

frontend/src/components/common/Footer.jsx
Closes #326 
Added dark theme for Footer.jsx
https://github.com/user-attachments/assets/491a88d8-0e98-4b27-ac48-bae51ac71ac9
=> Added dark theme for Footer.jsx

frontend/src/components/form/Accountform.jsx
Closes #326 
Added dark theme for Footer.jsx
https://github.com/user-attachments/assets/4dd28974-ce3a-4855-84e5-4dcd64cfd575
=> Added dark theme for AccountForm.jsx

frontend/package.json, frontend/src/pages/AboutUs.jsx, frontend/src/pages/ContactUs.jsx
Closes #257 
Enhanced the Contact Us component with improved UI/UX and animations:
- Added Framer Motion animations for smoother transitions and interactions
- Implemented glassmorphism design with backdrop blur effects
- Added floating animated background elements
- Enhanced form input styling with icons and hover effects
- Improved responsive layout and visual hierarchy
- Added gradient text and button effects
- Implemented better form feedback animations
- Added decorative elements for visual interest
- Improved contact information section layout and styling
- **Fixed**: Removed excessive top spacing from the component for better layout consistency
[Screen Recording - Made with FlexClip (45).webm](https://github.com/user-attachments/assets/fc13e508-daf0-494e-8aa3-58f957015598)
- …
=> Contact us

frontend/src/pages/Home.jsx
Closes #331 
Added dark theme for Home.jsx (for Patient)
https://github.com/user-attachments/assets/2f247897-6086-41bf-8ada-df224229e75e
=> Added dark theme for Home.jsx (for Patient)

frontend/src/components/medicines/MedicineSummary.jsx, frontend/src/pages/MedicineDetails.jsx, frontend/tailwind.config.js
Closes #343 
Added dark theme for:
- MedicineDetails.jsx 
- MedicineSummary.jsx
https://github.com/user-attachments/assets/33730719-dd5f-42d7-99c2-88789d86ca92
=> Added dark theme for MedicineDetails.jsx and MedicineSummary.jsx

frontend/src/components/medicines/FeaturedProducts.jsx, frontend/src/components/medicines/ProductCard.jsx, frontend/src/components/medicines/TopProducts.jsx, frontend/src/pages/Medicines.jsx
Closes #342 
Added dark theme for below components
- Medicines.jsx, 
- FeaturedProducts.jsx, 
- TopProducts.jsx, 
- ProductCard.jsx
https://github.com/user-attachments/assets/ee9ad6c6-6638-493f-8b5b-511dd972baa6
=> Added dark theme for Medicines.jsx, FeaturedProducts.jsx, TopProducts.jsx, and ProductCard.jsx

frontend/src/components/diseasePrediction/Disease.jsx, frontend/src/components/diseasePrediction/Symptom.jsx
Closes #341 
Added dark theme for below components
- Disease.jsx,
- Symptom.jsx
https://github.com/user-attachments/assets/55daa060-31de-4fe8-b4b4-ff9364073df4
=> Added dark theme for Disease.jsx, and Symptom.jsx

frontend/src/components/cart/EmptyView.jsx, frontend/src/pages/Cart.jsx
Closes #345 
Added dark theme for MedicineDetails.jsx and EmptyView.jsx (Cart)
https://github.com/user-attachments/assets/2c2e612d-ed57-437f-8c3a-1eaeb9229093
=> Added dark theme for MedicineDetails.jsx and EmptyView.jsx (Cart)

frontend/src/components/form/Accountform.jsx
=> fix: hide password misaligned

frontend/src/components/common/Header.jsx
fix #350 
Closes #350 
Implemented the requirements
=> fix: header component has respective functionalities

frontend/src/components/cart/CartItem.jsx, frontend/src/components/cart/QuantityBox.jsx, frontend/src/pages/Cart.jsx
Closes #346 
Added dark theme for:
- CartItem.jsx, 
- QuantityBox.jsx, 
- Cart.jsx
Uploading Recording 2025-02-24 225001.mp4…
=> Added dark theme for CartItem.jsx, QuantityBox.jsx, and Cart.jsx

frontend/src/pages/MyWallet.jsx, frontend/src/pages/RecentTransactions.jsx
Closes #348 
- MyWallet.jsx
- RecentTransactions.jsx
https://github.com/user-attachments/assets/f7376597-e11c-4090-8aa1-f442179cfa66
=> Added dark theme for MyWallet.jsx and RecentTransactions.jsx

frontend/src/components/orders/OrderedItem.jsx, frontend/src/pages/MyOrders.jsx
Closes #355 
Added dark theme for:
-  MyOrders.jsx 
- OrderedItem.jsx
https://github.com/user-attachments/assets/562fe6d8-48ac-40d3-9b2f-d7442b53dbb2
=> Added dark theme for MyOrders.jsx and OrderedItem.jsx

frontend/src/pages/Doctors.jsx
Identified on local run
fix duplication error
initial error:
=> fix: Duplicate backgroundColor keys in the Doctors.jsx file

frontend/src/pages/Feedback.jsx
Closes #358 
Added dark theme for Feedback.jsx
Given the effort invested in testing and optimizing this page for a more comfortable user experience, I expect the label `medium`.
https://github.com/user-attachments/assets/5101df34-15e1-4f82-9d65-99aaf9e23df0
=> Added dark theme for Feedback.jsx

frontend/src/pages/Failed.jsx, frontend/src/pages/Success.jsx
Closes #356 
Added dark theme for:
-  Success.jsx 
- Failed.jsx
https://github.com/user-attachments/assets/f536bb26-9022-4663-a0b5-23c75e4f2613
=> Added dark theme for Success.jsx and Failed.jsx

frontend/src/pages/ErrorPage.jsx
Closes #357 
Added dark theme for ErrorPage.jsx
Uploading Recording 2025-02-24 235437.mp4…
=> Added dark theme for ErrorPage.jsx

frontend/src/pages/Doctors.jsx
Closes #369 
This PR resolves a bug where incorrect time slots were being displayed in the schedulable times section. Now, only the valid and available time slots are shown.
- Reworked the filtering mechanism to ensure only valid slots are displayed.
- Ensured that unavailable and irrelevant timings are excluded from the selection.
=> Fixed Bug - Accurate Display of Schedulable Timings

frontend/src/components/resetPassword/ResetPassword.jsx, frontend/src/index.css, frontend/src/pages/Cart.jsx, frontend/src/pages/Doctors.jsx, frontend/src/pages/Home.jsx, frontend/tailwind.config.js
Closes #336 
- Implemented dark theme for the **Schedule Appointment modal** to ensure a consistent UI.
- Applied dark theme styling to **MUI Alert** across **all pages** where dark mode is already implemented for better visual appeal.
- **Note**: Below is an example of how the Alert styling has been modified to match the dark theme.
https://github.com/user-attachments/assets/93bb52ce-3af9-484a-a044-a7be023846ca
https://github.com/user-attachments/assets/1a939fcc-9a07-4652-a746-c6003b95816c
https://github.com/user-attachments/assets/ad7a22d5-02fd-445e-b48b-a831fdd4af7c
=> Added Dark Theme for Schedule Appointment Modal & MUI Alert

backend/app.py, frontend/src/pages/Home.jsx, frontend/src/pages/MeetPage.jsx
Closes #368 
- After the meeting, the consultation fee was deducted from the patient's wallet but **not recorded in their wallet history**.  
- The doctor's wallet was **not updated** with the consultation fee and its history.  
- The **patient's money is deducted** and properly **added to their wallet history**.  
- The **doctor's wallet balance is updated**, and the transaction is **added to their wallet history**.  
This ensures accurate financial tracking for both doctors and patients.
https://github.com/user-attachments/assets/2db21008-07f2-40de-99b8-6095ff0ebbd1
=> Fix Wallet Transaction Issues After Meeting

frontend/src/pages/MeetPage.jsx
Closes #386 
Added dark theme for MeetPage.jsx
https://github.com/user-attachments/assets/ac0d74a7-7ffa-4444-8be6-fda117ef4de5
https://github.com/user-attachments/assets/ecdc806f-e84c-4915-a464-fdf936a245d5
=> Feature/meet page.jsx dark theme

frontend/src/pages/Privacy.jsx
Closes #384 
Added dark theme for Privacy.jsx
https://github.com/user-attachments/assets/8ae43a9d-1790-40a5-a349-4260dd6f1a9c
=> Added dark theme for Privacy.jsx

frontend/src/components/common/Header.jsx, frontend/src/pages/DeleteAccount.jsx, frontend/src/routes/RouterRoutes.jsx
Closes #367 
- Created a new **Delete Account** page.
- Secured the page by allowing access **only to logged-in users**.
- Integrated the **account deletion option** in the account dropdown for easy access.
- Ensured that after account deletion, the user is logged out and the page **reloads to clear old data**.
https://github.com/user-attachments/assets/1152d4ad-7df1-4349-9f2f-6efdc0799fe4
https://github.com/user-attachments/assets/23e420d8-16cf-4a73-a336-2b243dc7db9c
=> Implemented logic to  Allow Users to Delete Their Account (Frontend)

backend/app.py, frontend/src/pages/Feedback.jsx, frontend/src/pages/LandingPage.jsx
Closes #366 
- Added a route to delete both doctor and patient accounts.
- **Doctor Account Deletion:** Removes their upcoming appointments from associated patients.
- **Patient Account Deletion:** Removes their upcoming appointments from associated doctors.
- Ensured that all feedback left by the user is anonymized upon deletion.
https://github.com/user-attachments/assets/a54ae8d4-e733-40c6-8ccd-bba953d23837
https://github.com/user-attachments/assets/1fc1ed2b-1a31-4e8f-956b-12b15eedb109
=> Implemented logic to Allow Users to Delete Their Account (Backend)
